### ISSUE TITLE
K-means++ for initial cluaters

### ISSUE THREAD

**Issue by stebogit** [solzimer/skmeans#1]
@solzimer are you planning to add any algorithm to [define the initial clusters](https://en.wikipedia.org/wiki/Determining_the_number_of_clusters_in_a_data_set), besides the random approach?
It seems the [K-means++](https://en.wikipedia.org/wiki/K-means%2B%2B) algo is a good one, which speed up the calculation and increase the probabilities to reach a global-optimum.

**Comment by solzimer** [comment]
Hi @stebogit, skmeans was initially intended as a first approach for the incremental version of the k-means algorythm, so it could be plugged into the [swstats](https://github.com/solzimer/swstats). That means there was no plans to go that way, but reading the links you have provided, it seems pretty interesting and "easily" doable.

I'll do some experiments and see how it fits, so I can include the kmeans++ as an optional initial cluster selection.

Thanks for the info!

**Comment by solzimer** [comment]
These are the performance results for all the implemented variants of skmeans against other modules:

```
Simple dataset with k = 3
skmeans x 3,776 ops/sec ±1.00% (85 runs sampled)
skmeans kmrand x 472 ops/sec ±1.02% (83 runs sampled)
skmeans++ x 909 ops/sec ±1.15% (84 runs sampled)
node-kmeans x 2,419 ops/sec ±1.82% (81 runs sampled)
ml-kmeans x 81.30 ops/sec ±0.97% (66 runs sampled)
cluster-kmeans x 1,481 ops/sec ±1.38% (77 runs sampled)
Fastest is skmeans

Complex dataset with k = 16
skmeans x 1,929 ops/sec ±0.91% (83 runs sampled)
skmeans kmrand x 694 ops/sec ±1.13% (84 runs sampled)
skmeans++ x 188 ops/sec ±1.03% (79 runs sampled)
node-kmeans x 1,232 ops/sec ±1.62% (81 runs sampled)
ml-kmeans x 80.01 ops/sec ±1.20% (65 runs sampled)
cluster-kmeans x 319 ops/sec ±1.88% (69 runs sampled)
Fastest is skmeans
```

**Comment by stebogit** [comment]
@solzimer nice comparison! 👍 
However the big drop in performance compared to the other libraries and even your own variants makes me wonder, did you evaluate performances before or after the selection of the initial centroids?
Because technically `kmeans++`, for example, is not part of `k-means` algorithm itself, but a separate previous step specifically designed to improve its performances (compared to the simple random selection for instance).

BTW, is there a way to test and estimate the probability/efficacy of the modules to find a global-optimum instead of a local-optimum?
I haven't find yet a good way to do it, due to the variability of the output on random distributed points. However I believe a "well-separated" dataset like [this](https://gist.githubusercontent.com/stebogit/64528eee185381724dbf9d407eac5e18/raw/fdcd7f7f45661151482ca8387efc8c0365222355/well-separated.js) (see [on the map](http://bl.ocks.org/d/e59f42fb68c331d825b6cd3db8724440)) might help to obtain consistent and repetitive results.

**Comment by solzimer** [comment]
@stebogit kmeans++ isn't really intended to improve the performance of kmeans itself, but to find a better final clustering, as it (simplifiying) tries to select those initial centroids with the maximum distance between each others.

This better initial selection may come (but not always) with the consequence that less iterations are required for the skmeans to converge.

Take a look at this simple test:

```
Simple data (k=3)
skmeans default         => 1.936
skmeans kmrand          => 1.929
skmeans kmpp            => 3

Complex data (k=16)
skmeans default         => 2
skmeans kmrand          => 2
skmeans kmpp            => 1
```
In the first test, random initialization takes an average of 2 iterations to converge, and kmeans++ takes 3, while in the second test, kmeans++ needs only one iteration.

There's an explanation (somewhat): The first test has well defined cluster groups, but random initilization, half of the time, ends up with a poor clustering result (two centroids being almost the same). Kmeans++ on the other way, always find the optimal groups. Random converges faster, but with totally incorrect clusters.

The second dataset is uniformly distributed, so all the methods find good cluster grouping, but due to better selection of kmeans++, it needs less iterations.

**Comment by stebogit** [comment]
@solzimer thanks for the explanation.

> Kmeans++ on the other way, always find the optimal groups. Random converges faster, but with totally incorrect clusters.

This is totally not my field of expertise, so I'll ask and it might sound stupid, but what's the point of running the algorithm knowing that often you'll get "totally incorrect clusters"?
Is there a particular kind of applications where you need just _any_ clustering?

Back to my second question, do you have any suggestion on how to evaluate, programmatically, the quality of the final clusters? Is there a definition of "correct" or "good" clustering?
I'd like to add some test to the module I'm working on, [`@turf/clusters-kmeans`](https://github.com/Turfjs/turf/tree/master/packages/turf-clusters-kmeans), where I adopted `skmeans`.

**Comment by solzimer** [comment]
I tend to exagerate my words 😛. What I really meant was that half of the times, depending on the dataset, random cluster initialization will get stuck at a local-optimum. This is not really a bad thing (even it can help discover outlier points), but is something one must deal when clustering with k-means.

Why use it? Its name says it all, it's "Simple K-Means": Simple to implement and understand, and the fastest of all the clustering algorythms out there. And by fastest, I mean 100x faster than other more sophisticated methods, like DBSCAN, or Kohonnen Neural Networks (SOM Networks). In most cases, you don't need global-optimum clustering, you just need clustering.

You can always apply some heuristics to your data prior to run kmeans (a.k.a pre-select initial centroids based on the meaning of your data), or even use another distance function (Something that discards points if one centroid is dense enough, because you want similar dense clusters)... And here is the point: What do you mean by "good" or "bad" clustering? It depends heavily on the meaning of your dataset, and what you expect to get.

In your particular case, I see the problem... You should use kmeans++ or run three or more times kmeans and take the result that provides the best metrics that applies to the case: Distance between centroids, and density of the clusters.

By the way, I've updated the "kmrand" method and these are the final results:
```javascript
skmeans x 3,625 ops/sec ±1.32% (83 runs sampled)
skmeans kmrand x 2,613 ops/sec ±2.93% (65 runs sampled)
skmeans++ x 775 ops/sec ±1.15% (84 runs sampled)
node-kmeans x 2,356 ops/sec ±1.84% (81 runs sampled)
ml-kmeans x 71.99 ops/sec ±1.00% (70 runs sampled)
cluster-kmeans x 1,411 ops/sec ±1.39% (80 runs sampled)
Fastest is skmeans
```

**Comment by solzimer** [comment]
@stebogit Another bug was found on k-means++. Now is working as intended. This is the run with your datasets:

```javascript
Simple data (k=3)
skmeans default		=> 2.634
skmeans kmrand		=> 2.724
skmeans kmpp		=> 1.395

Complex data (k=16)
skmeans default		=> 16.271
skmeans kmrand		=> 16.322
skmeans kmpp		=> 13.98
```
On both cases, although initial cluster selection is slower, kmeans++ converges faster.

And these are the results of the clustering:

[random init with random data](http://imgur.com/snVyZl7)
[kmeans++ with random data](http://imgur.com/VitkMJb)
[random init with well separated data](http://imgur.com/MyFKqPJ)
[kmeans++ init with well separated data](http://imgur.com/X6UA47E)

**Comment by stebogit** [comment]
That's great @solzimer! Thanks for the update.  👍
