### ISSUE TITLE
Same run gives different results

### ISSUE THREAD

**Issue by barocsi** [solzimer/skmeans#16]
For me each run of the same dataset gives different results. Is this due to the kmpp initialisation algorithm? Is there a seed that can be passed in this case? Thanks.

**Comment by solzimer** [comment]
Hi @barocsi,

This is working as intended. By default, kmeans initializes clusters randomly, so it may result in diferent final clusters. You can pass your own cluster initialization in the third parameter:

```javascript
let data = [4, 5, 6, 7, 10, 50, 21, 45, 32];
skmeans(data, 3, [7, 21, 32]);
```

In this case, as initial centroids are fixed, multiple runs will give you the same results.

For "kmpp", cluster initialization is performed by the algorithm in order to minimize the number of iterations to reach a local minimum.

**Comment by barocsi** [comment]
Thanks, meanwhile I did pretty much the same, generated my own centroids based on sample data with a random seed to be able to reproduce.
