### ISSUE TITLE
[0, 0] centroid

### ISSUE THREAD

**Issue by stebogit** [solzimer/skmeans#2]
@solzimer I used this [`dataset`](https://gist.githubusercontent.com/stebogit/567084a250ba59a49be12ba0870a183a/raw/0a9bfbd33f54239ff7f7db926ba9525988061e09/random%2520pts) (500 random points) for this simple test:
```js
var result = skmeans(dataset(), 16);
console.log(result.centroids);
```
However I noticed sometimes one or two centroid are set to `[0, 0]`, which is completely out of range (here a graphical representation of the [result](http://bl.ocks.org/d/ffa0031b691657e90bfa63839c1b1df8)).
I tried to debug the code to trace the issue (I believe it's a bug), but I couldn't find any useful hint.

Could you please check this out?
Due to the indeterminability of the output, unfortunately I can't give you a more specific example to better highlight the issue, but please let me know if I can be of help.

**Comment by solzimer** [comment]
Yeah, it's a "bug" that happens when none of the points are assigned to an initial centroid because some of the other centroids are a better choice. 

This happens when, during cluster initialization, two initial centroids are the same. It has been corrected, adding a new initialization option:

```javascript
var result = skmeans(dataset(), 16,"kmrand");
console.log(result.centroids);
```
this avoids two equals centroids in random initialization. In the case of the k-means++, I'm working on solving the same issue.

Thanks for the feedback!

**Comment by stebogit** [comment]
Thanks @solzimer.

Out of curiosity, why did you decide to have the check at initialization only on user input, isn't having two identical initial centroid always an undesired result?

However, unless I'm missing something, couldn't the check be more simply like this:
```js
function kmrand(data, k) {
    const ks = [],
        len = data.length;
    let lst = {}, // already selected index list (object search is faster that in arrays)
        i = 0;
    while (i < k) {
        let idx = Math.floor(Math.random() * len);
        // add index/centroid to the list only if new
        if (!lst[idx]) {
            ks.push(data[idx]);
            lst[idx] = 'done';
            i++
        }
    }
    return ks;
}
```
Don't know if this would be faster that your solution though.

**Comment by solzimer** [comment]
For the first question: the skmeans function is intended to be as fast as possible, and thats why is so "ugly". There are more elegant implementations out there, but at the cost of lower performance. Following this philosophy, skmeans doesn't do any safety check on data, leaving to the user to provide a correct input. That's why data validation is optional.

On the second question: Your implementation is indeed faster, but doesn't provide a safe method to avoid equal centroids. Suppose you have this vector: v = [1,2,3,4,1]. Checking only indexes, you can end with centroids on v[0] and v[4]. They have different indexes, but the same value. Thats why I first remove all repeated values, then check we can get at least K centroids and finally, iterate until K different centroids have been provided.

But your implementation has given me some ideas to improve mine.

**Comment by stebogit** [comment]
@solzimer I see your point and the philosophy of the library, good to know! 👍 

I agree the user should be responsible of the validity of his/her own data.

However, and I might be wrong, I believe that if for some reason the input presents two equal, but distinct, points, the initial selection (random or not) should be allowed to select those two points, as long as they are not the same one. Thus I believe the validation doesn't need to check the values of the initial centroids, but only make sure each none is selected twice.
I don't think the `k-means` algorithm has any restriction on the value of the input points/data.

What do you think?

**Comment by solzimer** [comment]
@stebogit  I've updated the code to avoid index repetition on default cluster initialization. Therefore, it's only up to the user to ensure all values are distinct.

**Comment by stebogit** [comment]
@solzimer I updated my code with the latest `skmeans` version (0.9.2 right?), however I regret to say this issue persists, actually is constant: when using the `kmpp` function all the selected initial centroids are now always equals (i.e. the same point), although they are not always the same pair. The output then has always at least one `[0, 0]` point as centroid (see [here](http://bl.ocks.org/d/2a01cfc0e687808875ede01c05ddc556), centroids have the star marker).
It seems the issue is related to [this line](https://github.com/solzimer/skmeans/blob/master/kinit.js#L75), where `idx` gets incremented only by one so the next line always pushs `prs[0].v`, i.e. the first point .
I'm wondering, couldn't/shouldn't the `kmpp` exclude the already selected points in the next iteration? This way it would be impossible to select twice the same point.

Moreover, in any case (even using `kmrand` or the default random selection) the centroids correspond always to points of the dataset (which I believe is wrong, not only in my case), like [this](http://bl.ocks.org/d/3bc81088211b40e211bc698ff1fdc910).

*p.s.* it would be helpful if you added tags to the project so it'll be clear which version is the latest.

**Comment by solzimer** [comment]
Kmeans++ current code is experimental. I've based the implementation on the official [paper](http://theory.stanford.edu/~sergei/papers/kMeansPP-soda.pdf) and some Python implementations, since the explanation on the paper is really poor, so there's probably some bugs like this (the algorythm itself should prevent initial centroid repetition by the way it works).

I'll take a look on the other issue,

**Comment by solzimer** [comment]
@stebogit On version 0.8.1 I introduced a critical bug on recalculating new centroids, that leads to a complete erroneous results.

It has been corrected and now results are pretty consistent even with random initial clusters. Here you can see your dataset classified with random and km++:

[random](http://imgur.com/yiQlKkJ)
[kmpp](http://imgur.com/pUbTYNM)
